
"""add_composite_indexes

Revision ID: 8a1ff00e1b6b
Revises: 0008_add_telegram_enterprise_tables
Create Date: 2026-05-27 21:18:21.064160

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a1ff00e1b6b'
down_revision = '0008_add_telegram_enterprise_tables'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_conversations_instance_chatwoot_active', 'conversations', ['instance_id', 'chatwoot_conversation_id', 'is_active'], unique=False)
    op.create_index('ix_conversations_instance_platform_active', 'conversations', ['instance_id', 'platform_conversation_id', 'is_active'], unique=False)
    op.create_index('ix_enterprise_bale_sessions_user_route_status', 'enterprise_bale_sessions', ['user_id', 'route_key', 'status'], unique=False)
    op.create_index('ix_enterprise_bale_users_instance_state', 'enterprise_bale_users', ['instance_id', 'current_state'], unique=False)
    op.create_index('ix_enterprise_document_assets_instance_type_active_sort', 'enterprise_document_assets', ['instance_id', 'asset_type', 'is_active', 'sort_order'], unique=False)
    op.drop_index(op.f('ix_enterprise_manual_groups_sort_order'), table_name='enterprise_manual_groups')
    op.create_index('ix_enterprise_manual_groups_sort_order', 'enterprise_manual_groups', ['instance_id', 'sort_order'], unique=False)
    op.create_index('ix_enterprise_telegram_sessions_user_route_status', 'enterprise_telegram_sessions', ['user_id', 'route_key', 'status'], unique=False)
    op.create_index('ix_enterprise_telegram_users_instance_state', 'enterprise_telegram_users', ['instance_id', 'current_state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_enterprise_telegram_users_instance_state', table_name='enterprise_telegram_users')
    op.drop_index('ix_enterprise_telegram_sessions_user_route_status', table_name='enterprise_telegram_sessions')
    op.drop_index('ix_enterprise_manual_groups_sort_order', table_name='enterprise_manual_groups')
    op.create_index(op.f('ix_enterprise_manual_groups_sort_order'), 'enterprise_manual_groups', ['sort_order'], unique=False)
    op.drop_index('ix_enterprise_document_assets_instance_type_active_sort', table_name='enterprise_document_assets')
    op.drop_index('ix_enterprise_bale_users_instance_state', table_name='enterprise_bale_users')
    op.drop_index('ix_enterprise_bale_sessions_user_route_status', table_name='enterprise_bale_sessions')
    op.drop_index('ix_conversations_instance_platform_active', table_name='conversations')
    op.drop_index('ix_conversations_instance_chatwoot_active', table_name='conversations')
    # ### end Alembic commands ###
