
"""add contacts_first_synced_at to instance_runtime_state

Revision ID: 5b8f2dfaae9f
Revises: a01d22d600e9
Create Date: 2026-06-27 21:35:06.255720

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b8f2dfaae9f'
down_revision = 'a01d22d600e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instance_runtime_state', sa.Column('contacts_first_synced_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instance_runtime_state', 'contacts_first_synced_at')
    # ### end Alembic commands ###



