
"""add_last_enterprise_sms_sync_at

Revision ID: ff196af55240
Revises: 8a1ff00e1b6b
Create Date: 2026-05-27 21:35:56.044443

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff196af55240'
down_revision = '8a1ff00e1b6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instance_runtime_state', sa.Column('last_enterprise_sms_sync_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instance_runtime_state', 'last_enterprise_sms_sync_at')
    # ### end Alembic commands ###
